#!/usr/bin/bash

set -x

###
# $1 needs to point to the PLUGIN_CONFIG file
#
cfg_file=$1
if [ -z "$cfg_file" ]; then
    cfg_file="PLUGIN_CONFIG"
    for file in "${cfg_file}" "../${cfg_file}"
    do
        if [ -e "$file" ]; then
            cfg_file=$file
            break
        fi
    done

    if [ ! -f "${cfg_file}" ]; then
        echo "Could not file CONFIG file"
        exit 1
    fi
fi

#source "${cfg_file}"

PROJ_LOWER=${SF_PROJECT,,}

cat <<_HERE_
SF_PROJECT=${SF_PROJECT}
SF_PROJ_LOWER=${PROJ_LOWER}
SF_VERSION=${SF_PROJECT}
_HERE_
