#!/usr/bin/bash -x

# Assume we are sitting in build
top=$1
[ -z "$top" ] && top=..

scripts="${top}/scripts"

if [ -z "$SF_PROJECT" ]; then
  eval $(${scripts}/project_vars.sh -exp sh)
fi

pkg=${SF_PROJ_LOWER}
pkg_src=${top}/packaging

dir=${pkg}_${SF_VERSION}_linux-amd64

rm -rf ${dir}
mkdir ${dir}

# VST3
mkdir -p ${dir}/usr/lib/vst3
cp -R ${SF_VST3_BUILD_PATH}/* ${dir}/usr/lib/vst3

# Control file
mkdir ${dir}/DEBIAN
${scripts}/expand_file.sh ${pkg_src}/debian/control > ${dir}/DEBIAN/control

mkdir -p ${dir}/usr/share/doc/${pkg}

# changelog
# place holder until I can come up with something better
chng=${dir}/usr/share/doc/${pkg}/changelog

cat <<_END_ > ${chng}
${pkg} (${SF_VERSION}) stable; urgency=low

  [ SolidFuel ]
_END_
git log --pretty=format:%s `git tag --sort=-committerdate | \
    head -1`...`git tag --sort=-committerdate | head -2 | \
    awk '{split($0, tags, "\n")} END {print tags[1]}'` | \
    awk '{ print "  * ", $0 }' | grep -v "Merge pull request" >>  ${chng}

date_string=`date -R`
cat <<_OUTRO_ >> ${chng}

 -- SolidFuel <solidfuelplugins@gmail.com>  ${date_string}
_OUTRO_

gzip --best --no-name ${dir}/usr/share/doc/${pkg}/changelog

# copyright
${scripts}/expand_file.sh ${pkg_src}/debian/copyright > ${dir}/usr/share/doc/${pkg}/copyright

# CREATE
dpkg-deb --root-owner-group --build ${dir}

# Output tie file name for other steps
[ -n "${GITHUB_OUTPUT}" ] && echo "deb_file=${dir}.deb" >> ${GITHUB_OUTPUT}
