#!/usr/bin/bash -x

# Assume we are sitting in build
TOP=$1
[ -z "$TOP" ] && TOP=..

if [ -z "$SF_PROJECT" ]; then
  eval $(${TOP}/scripts/project_vars "" 1)
fi

PKG=${SF_PROJ_LOWER}
PKG_SRC=${TOP}/packaging

DIR=${PKG}_${SF_VERSION}_linux-amd64

rm -rf ${DIR}
mkdir ${DIR}

# VST3
mkdir -p ${DIR}/usr/lib/vst3
cp -R Source/${SF_PROJECT}_artefacts/Release/VST3/* ${DIR}/usr/lib/vst3

# Control file
mkdir ${DIR}/DEBIAN
${TOP}/scripts/expand_file ${PKG_SRC}/debian/control > ${DIR}/DEBIAN/control

mkdir -p ${DIR}/usr/share/doc/${PKG}

# changelog
# place holder until I can come up with something better
CHNG=${DIR}/usr/share/doc/${PKG}/changelog

cat <<_END_ > ${CHNG}
${PKG} (${SF_VERSION}) stable; urgency=low

  [ SolidFuel ]
_END_
git log --pretty=format:%s `git tag --sort=-committerdate | \
    head -1`...`git tag --sort=-committerdate | head -2 | \
    awk '{split($0, tags, "\n")} END {print tags[1]}'` | \
    awk '{ print "  * ", $0 }' | grep -v "Merge pull request" >>  ${CHNG}

DATE=`date -R`
cat <<_OUTRO_ >> ${CHNG}

 -- SolidFuel <solidfuelplugins@gmail.com>  ${DATE}
_OUTRO_

gzip --best --no-name ${DIR}/usr/share/doc/${PKG}/changelog

# copyright
${TOP}/scripts/expand_file ${PKG_SRC}/debian/copyright > ${DIR}/usr/share/doc/${PKG}/copyright

# CREATE
dpkg-deb --root-owner-group --build ${DIR}

# Output
[ -n "${GITHUB_OUTPUT}" ] && echo "deb_file=${DIR}.deb" >> ${GITHUB_OUTPUT}
